[package]

name = "conduit-static"
version = "0.9.0-alpha.3"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
description = "Middleware for serving static files for conduit"
repository = "https://github.com/conduit-rust/conduit-static"
license = "MIT"

[dependencies]
conduit = "0.9.0-alpha.5"
conduit-mime-types = "0.7"
time = { version = "0.2", default-features = false, features = ["std"] }
filetime = "0.2"

[dev-dependencies]
civet = "0.12.0-alpha.5"
conduit-test = "0.9.0-alpha.5"
tempdir = "0.3"
